### ISSUE TITLE
karma listed in dependencies instead of devDependencies

### ISSUE THREAD

**Issue by amakhrov** [litixsoft/karma-mocha-reporter#44]
It forces `npm` to include `karma` package into shrinkwrap.

However, it doesn't seem that karma is used by the lib itself.
So the suggestion is to remove karma from dependencies, or move to devDependencies (like in other karma plugins: [karma-mocha](https://github.com/karma-runner/karma-mocha/blob/master/package.json#L23), [karma-webpack](https://github.com/webpack/karma-webpack/blob/master/package.json#L9)).

**Comment by 4kochi** [comment]
Well, never thought it would be a problem since karma-mocha-reporter itself is always a dev dependency in a normal project. But I also never used npm shrinkwrap. 

I guess the correct behavior would be to add `karma` as a peerDependency. Then the user of a project can decide itself were to put the `karma` dependency. I will check what npm shrinkwrap does in this case.

**Comment by amakhrov** [comment]
Maybe it's an issue with npm - I also expected that since karma-mocha-reporter is a dev dependency, its own dependencies would be treated as 'dev' and excluded from shrinkwrap. However, with the stable node/npm it's not the case.
Funny enough that karma-mocha-reporter itself is excluded - by karma is not :)

**Comment by 4kochi** [comment]
From the npm documentation:

"Since npm shrinkwrap is intended to lock down your dependencies for production use, devDependencies will not be included unless you explicitly set the --dev flag when you run npm shrinkwrap."

So it could really be an npm problem. I will have a look this weekend.

**Comment by amakhrov** [comment]
In any case I'm not sure it's correct to have karma as a dependency in this particular case.

Thanks.

**Comment by rosston** [comment]
I think karma shows up in your shrinkwrap because node 5 ships with npm 3. Because npm 3 flattens out the node_modules directory, there are some weird effects when shrinkwrapping.

I work on a project where we have special scripts set up for installing new modules just so that `fsevents` doesn't end up in the top level of the shrinkwrap, and that package is an optional sub-dependency 2 or 3 packages down from one of our top-level dependencies.

**Comment by 4kochi** [comment]
Moved `karma` to peerDependencies. Now you can add `karma` and `karma-mocha-reporter` as devDependencies in your project and they will be excluded by `npm-shrinwrap`
